### ISSUE TITLE
Fallo al compilar.

### ISSUE THREAD

**Issue by eric-ao** [Arquisoft/viade_es4b#58]
He conseguido que funcionen los tests, es decir que los ejecute (pasen o no pasen), pero ahora cuando intento lanzar la aplicacion me da este error:

> ./node_modules/shacl-js/shacl.js
> TypeError: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

Esta en la rama testsEric.

**Comment by cidinene** [comment]
Sobre que rama?

**Comment by eric-ao** [comment]
sobre la rama testsEric

**Comment by cidinene** [comment]
El fallo que indica es de transpilación.. creo que hay problema entre la versión de react y la de babel. Con el siguiente package.json el problema de compilación está resuelto aunque da un problema después en la página welcome:
_{
  "name": "viade_0",
  "version": "0.1.0",
  "homepage": "https://arquisoft.github.io/viade_0/",
  "private": true,
  "dependencies": {
    "@babel/core": "7.1.6",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.8.0",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@inrupt/solid-react-components": "0.5.0",
    "@inrupt/solid-sdk-forms": "0.1.0",
    "@inrupt/solid-style-guide": "^0.1.34",
    "@rdfjs/data-model": "^1.1.1",
    "@shexjs/core": "^1.0.0-alpha.4",
    "@solid/query-ldflex": "2.6.0",
    "@svgr/webpack": "2.4.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "babel-eslint": "10.0.3",
    "babel-loader": "8.0.6",
    "bfj": "6.1.1",
    "case-sensitive-paths-webpack-plugin": "2.1.2",
    "chalk": "2.4.1",
    "dotenv": "^6.2.0",
    "dotenv-expand": "^4.2.0",
    "eslint": "^6.6.0",
    "flag-icon-css": "^3.3.0",
    "fork-ts-checker-webpack-plugin-alt": "0.4.14",
    "fs-extra": "7.0.0",
    "google-maps-react": "2.0.2",
    "i18next": "^15.0.4",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-xhr-backend": "^2.0.1",
    "identity-obj-proxy": "3.0.0",
    "moment": "^2.24.0",
    "n3": "^1.3.0",
    "normalize.css": "^8.0.1",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "pnp-webpack-plugin": "1.1.0",
    "react": "16.8.4",
    "react-app-polyfill": "^0.2.2",
    "react-click-outside": "^3.0.1",
    "react-dev-utils": "^7.0.1",
    "react-dom": "16.8.4",
    "react-i18next": "^10.1.2",
    "react-modal": "^3.8.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.0",
    "react-toastify": "^5.3.0",
    "react-transition-group": "^4.1.1",
    "shacl-js": "0.0.1",
    "shx": "0.3.2",
    "solid-auth-client": "^2.3.0",
    "styled-components": "^4.1.3",
    "webpack": "4.41.2",
    "webpack-dev-server": "3.9.0"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js",
    "docs": "shx rm -rf build/docs && asciidoctor -D build/docs -a imagesdir=./images -r asciidoctor-diagram src/docs/index.adoc && shx cp -R src/docs/images build/docs",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "module-resolver",
        {
          "root": [
            "./src"
          ],
          "alias": {
            "@components": "./src/components",
            "@containers": "./src/containers",
            "@util-components": "./src/components/Utils",
            "@services": "./src/services",
            "@layouts": "./src/layouts",
            "@contexts": "./src/contexts/",
            "@hocs": "./src/hocs",
            "@utils": "./src/utils",
            "@hooks": "./src/hooks",
            "@constants": "./src/constants"
          }
        }
      ]
    ]
  },
  "devDependencies": {
    "@babel/preset-react": "^7.8.3",
    "babel-plugin-module-resolver": "^4.0.0",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "1.0.0",
    "eslint": "5.6.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-config-react-app": "^3.0.6",
    "eslint-config-xo": "^0.25.0",
    "eslint-loader": "2.1.1",
    "eslint-plugin-flowtype": "2.50.1",
    "eslint-plugin-import": "2.14.0",
    "eslint-plugin-jsx-a11y": "6.1.2",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "7.11.1",
    "file-loader": "2.0.0",
    "html-webpack-include-assets-plugin": "^1.0.6",
    "html-webpack-plugin": "4.0.0-alpha.2",
    "husky": "^1.3.1",
    "jest": "^24.1.0",
    "jest-dom": "^3.1.2",
    "jest-pnp-resolver": "1.0.1",
    "jest-resolve": "23.6.0",
    "mini-css-extract-plugin": "0.4.3",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "postcss-preset-env": "6.3.1",
    "postcss-safe-parser": "4.0.1",
    "prettier": "^1.18.2",
    "react-testing-library": "^6.0.0",
    "resolve": "1.8.1",
    "sass-loader": "7.1.0",
    "style-loader": "0.23.0",
    "terser-webpack-plugin": "1.1.0",
    "url-loader": "1.1.1",
    "webpack": "^4.41.2",
    "webpack-dev-server": "3.1.14",
    "webpack-manifest-plugin": "2.0.4",
    "workbox-webpack-plugin": "3.6.3"
  }
}_

**Comment by eric-ao** [comment]
He probado ese package y me dicen que me falta un modulo (al menos, ya que quizas al solucionar el problema con ese modulo aparezcan otros). 
El modulo en cuestión es: babel-preset-react-app/webpack-overrides
Y si intento hacer:
> npm install babel-preset-react-app/webpack-overrides
Me da este error:

> npm ERR! Error while executing:
> npm ERR! D:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/babel-preset-react-app/webpack-overrides.git
> npm ERR!
> npm ERR! Host key verification failed.
> npm ERR! fatal: Could not read from remote repository.
> npm ERR!
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR!
> npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2020-03-13T08_58_57_094Z-debug.log
